//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KriptoGuvercini.data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesEN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KriptoGuvercini.data.ResourcesEN", typeof(ResourcesEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything you write on the Internet is being watched &amp; recorded..
        /// </summary>
        public static string about1 {
            get {
                return ResourceManager.GetString("about1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keys are created for you and stored using the.
        /// </summary>
        public static string about10 {
            get {
                return ResourceManager.GetString("about10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to algorithm, using the password you set during registration. Your message gets encrypted with the receivers public key. Therefore, the message.
        /// </summary>
        public static string about11 {
            get {
                return ResourceManager.GetString("about11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to meet up on Saturday?.
        /// </summary>
        public static string about12 {
            get {
                return ResourceManager.GetString("about12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to looks like.
        /// </summary>
        public static string about13 {
            get {
                return ResourceManager.GetString("about13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to everyone else. The message only gets decrypted when the receiver reads it and can be deleted afterwards (we strongly recommend it)..
        /// </summary>
        public static string about14 {
            get {
                return ResourceManager.GetString("about14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long story short, everything you write using Crypto Pigeon is secure..
        /// </summary>
        public static string about15 {
            get {
                return ResourceManager.GetString("about15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whenever you message someone, your message gets stored on databases..
        /// </summary>
        public static string about2 {
            get {
                return ResourceManager.GetString("about2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These messages can be seen by site owners. Or...
        /// </summary>
        public static string about3 {
            get {
                return ResourceManager.GetString("about3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They can be seen if.
        /// </summary>
        public static string about4 {
            get {
                return ResourceManager.GetString("about4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to databases get hacked..
        /// </summary>
        public static string about5 {
            get {
                return ResourceManager.GetString("about5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theses messages can be seen by people who are listening. And most importantly...
        /// </summary>
        public static string about6 {
            get {
                return ResourceManager.GetString("about6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What you write can be used (and will be used) against you by people or organizations with lots of resources..
        /// </summary>
        public static string about7 {
            get {
                return ResourceManager.GetString("about7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The messages you write can&apos;t be read by anyone but the receiver..
        /// </summary>
        public static string about8 {
            get {
                return ResourceManager.GetString("about8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you register, unique 2048-bit.
        /// </summary>
        public static string about9 {
            get {
                return ResourceManager.GetString("about9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto Pigeon is created for you to chat securely. When you sign up, unique keys are created for you and every message is sent after being encrypted. Your messages can only be read by the receiver; they can&apos;t be read by the site owners, your ISP or anyone inbetween..
        /// </summary>
        public static string intro {
            get {
                return ResourceManager.GetString("intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your RSA keys have been created..
        /// </summary>
        public static string introLoggedIn {
            get {
                return ResourceManager.GetString("introLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto Pigeon.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto Pigeon is licensed under GNU/GPL2. You can find the source code in our.
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
    }
}
