//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KriptoGuvercini.data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesTR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesTR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KriptoGuvercini.data.ResourcesTR", typeof(ResourcesTR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internette yazdığınız herşey izleniyor &amp; kayıt altına alınıyor..
        /// </summary>
        public static string about1 {
            get {
                return ResourceManager.GetString("about1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anahtarları yaratılır ve.
        /// </summary>
        public static string about10 {
            get {
                return ResourceManager.GetString("about10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to algoritmasi ile şifrelenir (üye olurken yarattığınız şifre ile). Mesajınız yolladığınızda alıcınızın anahtarına göre şifrelenir ve şifreli haliyle kaydolur. Böylece yolladığınız.
        /// </summary>
        public static string about11 {
            get {
                return ResourceManager.GetString("about11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumartesi günü buluşmak ister misin?.
        /// </summary>
        public static string about12 {
            get {
                return ResourceManager.GetString("about12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mesajı, diğer herkes için.
        /// </summary>
        public static string about13 {
            get {
                return ResourceManager.GetString("about13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gibi görülür. Mesaj sadece okunacağı zaman, alıcı tarafından deşifrelenir ve okunduktan sonra silinebilir (tavsiye ederiz)..
        /// </summary>
        public static string about14 {
            get {
                return ResourceManager.GetString("about14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzun lafın kısası, Kripto Güvercini ile yazdığınız herşey güvendedir..
        /// </summary>
        public static string about15 {
            get {
                return ResourceManager.GetString("about15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal medyada, emaillerinizde birine mesaj attığınızda bu mesajlar veritabanlarında saklanır..
        /// </summary>
        public static string about2 {
            get {
                return ResourceManager.GetString("about2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu mesajlar site sahipleri tarafindan gorülebilir,.
        /// </summary>
        public static string about3 {
            get {
                return ResourceManager.GetString("about3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanları hacklenirse.
        /// </summary>
        public static string about4 {
            get {
                return ResourceManager.GetString("about4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kötü niyetli insanlar tarafından görülebilir,.
        /// </summary>
        public static string about5 {
            get {
                return ResourceManager.GetString("about5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajlarınız sizi dinleyen kişiler tarafından görülebilir. Ve en önemlisi...
        /// </summary>
        public static string about6 {
            get {
                return ResourceManager.GetString("about6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazdığınız herşey birsürü kaynağı olan kişiler ve gruplara açıktır ve aleyhinizde kullanılabilir (ve kullanılır)..
        /// </summary>
        public static string about7 {
            get {
                return ResourceManager.GetString("about7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kripto Güvercini kullanarak yazdığınız mesajlar başkaları tarafından okunamaz..
        /// </summary>
        public static string about8 {
            get {
                return ResourceManager.GetString("about8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye olduğunuzda size özel 2048 bit.
        /// </summary>
        public static string about9 {
            get {
                return ResourceManager.GetString("about9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kripto Güvercini başka insanlarla güvenle mesajlaşmanız için yaratılmıştır. Üye olduğunuzda size özel anahtarlar yaratılır ve yolladığınız mesajlar bu anahtarlarlar ile şifrelenir. Bu mesaj sadece alıcısı tarafından okunabilir; site sahipleri, internet sağlayıcınız veya aradaki herhangi birileri tarafından gorülemez..
        /// </summary>
        public static string intro {
            get {
                return ResourceManager.GetString("intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA anahtarlarınız oluşturuldu..
        /// </summary>
        public static string introLoggedIn {
            get {
                return ResourceManager.GetString("introLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kripto Güvercini.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kripto Güvercini GNU/GPL2 ile lisanslanmıştır. Kaynak kodunu .
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
    }
}
